config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  root 'users#index'
  resources :users
  resources :posts
  resources :users do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user,optional: true
  has_one_attached :image
  def self.ransackable_attributes(auth_object = nil)
    ["title", "body"]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_one_attached :image

  def self.ransackable_attributes(auth_object = nil)
    ["email", "name"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_sign_up_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    users_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected
    def configure_sign_up_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :set_q, only: [:index]
  def index
    @posts = @q.result(distinct: true)
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    # binding.pry
    @post.save
    redirect_to posts_path, notice: "投稿しました"
  end

  def edit 
  end
  
  def update
    @post.update(post_params)
    if @post.update(post_params)
      redirect_to posts_path, notice: '更新しました'
    else
      render :edit
    end
  end

  def destroy
    if @post.destroy
      redirect_to posts_path, notice: "削除しました"
    else
      render :new
    end
  end


  private
    def post_params
      params.require(:post).permit(:title, :body, :image)
    end

    def set_post
      @post = Post.find(params[:id])
    end

    def set_q
      @q = Post.ransack(params[:q])
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_parameters, only: [:new, :create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.

  protected
    def configure_sign_up_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
    end

    def after_sign_up_path_for(resource)
      users_path
    end
  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    new_user_registration_path
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show, :edit, :update, :destroy]
  before_action :set_q, only: [:index]
  
  def index
    # @users = User.all
    @users = @q.result(distinct: true)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def logout
    sign_out(current_user)
    redirect_to root_path
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confrimation, :image)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def set_q
      @q = User.ransack(params[:q])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Practice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/posts.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Practice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "posts/shared/header" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>User画面</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "users/shared/header" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>編集ページ</h1>
<%= form_with model:@post, url: post_path do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>

  <%= f.label :body %><br>
  <%= f.text_area :body %><br>

  <%= f.submit "更新する" %>
<% end %>

app/views/posts/index.html.erb
<h2>投稿一覧</h2>
<h3>検索</h3>
<%= search_form_for @q do |f| %>
  <%= f.label :title_cont, 'タイトル名' %>
  <%= f.search_field :title_cont %>
  <br>
  <%= f.submit '検索' %>
<% end %>
<% @posts.each do |post| %>
  <div class="card" style="width: 16rem;">
    <%= image_tag post.image, width:254 %>
    <div class="card-body">
      <h5 class="card-title"><%= link_to post.title, post_path(post) %></h5>
      <p class="card-text"><%= post.body %></p>
      <button type="button" class="btn btn-outline-primary"><%= link_to "詳細", post_path(post) %>
    </div>
  </div><br>
<% end %>

app/views/posts/new.html.erb
<h1>投稿する</h1>
<%= form_with model:@post, url: posts_path, method: :post  do |f| %>
  <%= f.file_field :image %><br>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>

  <%= f.label :body %><br>
  <%= f.text_area :body %><br>

  <%= f.submit "投稿する" %>
<% end %>

app/views/posts/shared/_header.html.erb
<nav class="level-right is-max-desktop navbar-light bg-light">
  <% if user_signed_in? %>
    <p class="level-item">
      <button type="button" class="btn btn-outline-primary"><%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete } %>
    </p>
    <p class="level-item">
      <button type="button" class="btn btn-outline-primary"><%= link_to "ユーザー一覧", users_path %>
    </p>
    <p class="level-item">
      <button type="button" class="btn btn-outline-primary"><%=  link_to "マイページ", user_path(current_user) %>
    </p>
    <p class="level-item">
      <button type="button" class="btn btn-outline-primary"><%= link_to "投稿一覧", posts_path %>
    </p>
    <p class="level-item">
      <button type="button" class="btn btn-outline-primary"><%= link_to  "投稿する", new_post_path %>
    </p>
  <% else %>
    <p class="level-item has-text-white">
      <button type="button" class="btn btn-outline-primary"><%= link_to "ログイン", new_user_session_path %>
    </p>
    <p class="level-item">
      <button type="button" class="btn btn-outline-primary"><%= link_to "新規登録", new_user_registration_path %>
    </p>
  <% end %>
</nav> 

app/views/posts/show.html.erb
<h2>詳細ページ</h2>
<%= image_tag @post.image, :size =>'320x200' %><br>
<%= @post.title %><br>
<%= @post.body %><br>
<%= link_to "編集する", edit_post_path(@post) %>
<%= link_to "削除", post_path(@post), data: { turbo_method: :delete } %>

app/views/users/edit.html.erb
<h1>プロフィール編集</h1>
<%= form_for(current_user, url: registration_path(current_user), html: { method: :put }) do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>

  <%= f.label :email %><br>
  <%= f.email_field :email %><br>

  <%= f.label :password %><br>
  <%= f.password_field :password %><br>

  <%= f.label :password_confirmation %><br>
  <%= f.password_field :password_confirmation %><br>

  <%= f.submit '更新する' %>
<% end %>

app/views/users/index.html.erb
<h1>User一覧</h1>
<h3>ユーザー検索</h3>
<%= search_form_for @q do |f| %>
  <%= f.label :name_cont, 'ユーザー名' %>
  <%= f.search_field :name_cont %>
  <br>
  <%= f.submit '検索' %>
<% end %>
<% @users.each do |user| %>
  <div class="card" style="width: 16rem;">
    <%= image_tag user.image, width:254 if user.image.attached? %>
    <div class="card-body">
      <h5 class="card-title"><%= link_to user.name, user_path(user) %></h5>
      <p class="card-text"><%= user.email %></p>
      <button type="button" class="btn btn-outline-primary"><%= link_to "詳細", user_path(user) %>
    </div>
  </div><br>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_header.html.erb
<nav class="level-right is-max-desktop navbar-light bg-light">
  <% if user_signed_in? %>
    <p class="level-item">
      <button type="button" class="btn btn-outline-primary"><%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete } %>
    </p>
    <p class="level-item">
      <button type="button" class="btn btn-outline-primary"><%= link_to "ユーザー一覧", users_path %>
    </p>
    <p class="level-item">
      <button type="button" class="btn btn-outline-primary"><%=  link_to "マイページ", user_path(current_user) %>
    </p>
    <p class="level-item">
      <button type="button" class="btn btn-outline-primary"><%= link_to "投稿一覧", posts_path %>
    </p>
    <p class="level-item">
      <button type="button" class="btn btn-outline-primary"><%= link_to  "投稿する", new_post_path %>
    </p>
  <% else %>
    <p class="level-item has-text-white">
      <button type="button" class="btn btn-outline-primary"><%= link_to "ログイン", new_user_session_path %>
    </p>
    <p class="level-item">
      <button type="button" class="btn btn-outline-primary"><%= link_to "新規登録", new_user_registration_path %>
    </p>
  <% end %>
</nav> 

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>詳細画面</h1>
<%= image_tag @user.image, :size =>'200x200' if @user.image.attached? %><br>
<%= @user.name %><br>
<%= @user.email %><br>
<% if @user == current_user %>
  <%= link_to "編集する", edit_user_path(@user) %>
<% end %>